module px4_msgs {
module msg {
module dds_ {

@topic
struct AirspeedValidated_ {
    unsigned long long timestamp;
    float indicated_airspeed_m_s;
    float calibrated_airspeed_m_s;
    float true_airspeed_m_s;
    octet airspeed_source;
    float calibrated_ground_minus_wind_m_s;
    float calibraded_airspeed_synth_m_s;
    float airspeed_derivative_filtered;
    float throttle_filtered;
    float pitch_filtered;
};

}; // dds_
}; // msg
}; // px4_msgs
