module px4_msgs {
module msg {
module dds_ {

@topic
struct VehicleOdometry_ {
    unsigned long long timestamp;
    unsigned long long timestamp_sample;
    octet pose_frame;
    float position[3];
    float q[4];
    octet velocity_frame;
    float velocity[3];
    float angular_velocity[3];
    float position_variance[3];
    float orientation_variance[3];
    float velocity_variance[3];
    octet reset_counter;
    octet quality;
};

}; // dds_
}; // msg
}; // px4_msgs
