module px4_msgs {
module msg {

@topic
struct VehicleAttitude {
    unsigned long long timestamp;
    unsigned long long timestamp_sample;
    float q[4];
    float delta_q_reset[4];
    octet quat_reset_counter;
};

}; // msg
}; // px4_msgs
