module px4_msgs {
module msg {
module dds_ {

@topic
struct VehicleCommandAck_ {
    unsigned long long timestamp;
    unsigned long command;
    octet result;
    octet result_param1;
    long result_param2;
    octet target_system;
    unsigned short target_component;
    boolean from_external;
};

}; // dds_
}; // msg
}; // px4_msgs
