module px4_msgs {
module msg {
module dds_ {

@topic
struct Wind_ {
    unsigned long long timestamp;
    unsigned long long timestamp_sample;
    float windspeed_north;
    float windspeed_east;
    float variance_north;
    float variance_east;
    float tas_innov;
    float tas_innov_var;
    float beta_innov;
    float beta_innov_var;
};

}; // dds_
}; // msg
}; // px4_msgs
