module px4_msgs {
module msg {
module dds_v116_ {

@topic
struct AirspeedValidated_ {
    unsigned long long timestamp;
    float indicated_airspeed_m_s;
    float calibrated_airspeed_m_s;
    float true_airspeed_m_s;
    float calibrated_ground_minus_wind_m_s;
    float true_ground_minus_wind_m_s;
    boolean airspeed_sensor_measurement_valid;
    octet selected_airspeed_index;
    float airspeed_derivative_filtered;
    float throttle_filtered;
    float pitch_filtered;
};

}; // dds_v116_
}; // msg
}; // px4_msgs
